### ISSUE TITLE
Exceptions and stuff (was Clicking on "Show tutor" sometimes ignored).

### ISSUE THREAD

**Issue by tico-tico** [lukasmonk/lucaschess#29] opened 2017-03-05 02:31 UTC
Sometimes when a tutor suggest a better move clicking on `There are XXX best moves` -> `Show tutor` just ignored.

I made this changes (marked with *# <--*) to **GestorEntMaq.py** to see wtf is going on:

```python
                    if siTutor:
                    
                        sys.stderr.write("TUTORR!") # <--
                    
                        tutor = Tutor.Tutor(self, self, jg, desde, hasta, False)

                        if self.aperturaStd:
                            liApPosibles = self.listaAperturasStd.listaAperturasPosibles(self.partida)
                        else:
                            liApPosibles = None
                        sys.stderr.write("1") # <--
                        if tutor.elegir(self.ayudas > 0, liApPosibles=liApPosibles):
                            sys.stderr.write("2") # <--
                            if self.ayudas > 0:  # doble entrada a tutor.
                                sys.stderr.write("3") # <--
                                self.reponPieza(desde)
                                self.ayudas -= 1
                                desde = tutor.desde
                                hasta = tutor.hasta
                                coronacion = tutor.coronacion
                                siBien, mens, jgTutor = Jugada.dameJugada(self.partida.ultPosicion, desde, hasta, coronacion)
                                if siBien:
                                    sys.stderr.write("4") # <--
                                    jg = jgTutor
                                    self.setSummary("SELECTTUTOR", True)
                        else:
                            sys.stderr.write("self.ayudas: " + str(self.ayudas) + "\n") # <--
                            sys.stderr.write("self.aperturaStd: " + str(self.aperturaStd) + "\n") # <--
                            sys.stderr.write("liApPosibles: " + str(liApPosibles) + "\n") # <--
                        sys.stderr.write("5") # <--
                        if self.configuracion.guardarVariantesTutor:
                            sys.stderr.write("6") # <--
                            tutor.ponVariantes(jg, 1 + self.partida.numJugadas() / 2)

                        del tutor
                        sys.stderr.write("7\n") # <--
```

Here is the result:

```
TUTORR!1234567
TUTORR!1234567
TUTORR!1234567
TUTORR!1234567
TUTORR!1234567
TUTORR!1self.ayudas: 2
self.aperturaStd: None
liApPosibles: None
567
```

So in a normal case it went through all the branches, in case of error it breaks with `self.aperturaStd==None`. I have no idea what that means.

**Comment by tico-tico** [comment] 2017-03-05 02:59
I'm using Komodo 8 as a tutor if it matters.

**Comment by lukasmonk** [comment] 2017-03-05 08:47
I use direct prints (running in pycharm or sciteru) or debug when things get tough.

I've been able to replicate the problem, adding sensitivity (999) to tutor (Options/Configuration).
It is necessary to test this previous to menu, because it can´t be necessary.

**Comment by lukasmonk** [comment] 2017-03-05 09:04
I have replaced 
line 778:   if (pointsBest - pointsUser) > 0:
with
            difpts = self.configuracion.tutorDifPts
            difporc = self.configuracion.tutorDifPorc
            if self.mrmTutor.mejorRMQue(rmUser, difpts, difporc):

**Comment by tico-tico** [comment] 2017-03-05 10:00
I can't test right now, but I still can't understand how this **if** related to the problem. Please take another look at the debug output. The things break on line 813. The bug is really unpredictable and I really don't know how to reproduce it properly.
BTW I have sensitivity 0 difference in points and 10 in percents.

**Comment by lukasmonk** [comment] 2017-03-05 10:37
This **if** determine if the tutor must work.

Previously:
- if difpoints > 0 then:
      - if second opportunity (self.chance) then shows a menu:
              -----> if you select tutor, then:
                       -----------> tutor routine test difpoints and difporc, in your case if difporc (10%) is greater than current difference, then exit, and doesn´t show tutor window.

**Comment by fonkap** [comment] 2017-03-05 12:54
Hello Lucas, hello Tico.

I think I've seen this problem before (or a very related one).
I think that if the position is mate and for any reason tutor finds a different mate, this problem appears.
I haven't got time to test your patch, but I have another one I think it can help.

In GestorEntMaq, line 765:
```
if not siElegido and self.siTutorActivado:
```
Change for:
```
mate = jg.posicion.siTerminada() and jg.siJaque
if not siElegido and self.siTutorActivado: #and not mate:
```
Then Tutor will never be offered if position is checkmate.
Please give me some time and I'll test the solution more and I'll provide some test cases.

Tico, could you confirm that the problem appears when the position is checkmate?
If not, could you provide a position (FEN) and configuration when the problem appears?

Greetings.

**Comment by lukasmonk** [comment] 2017-03-05 13:03
I have uploaded the last code.

**Comment by tico-tico** [comment] 2017-03-05 13:49
Here's the FEN `r1b2bnr/2p2kp1/p1ppp2p/4Pp2/3P4/4B3/PPP2PPP/RN1QK2R w KQ - 0 10`

If I play (for instance) pawn to c3 without @lukasmonk's fix from https://github.com/lukasmonk/lucaschess/issues/29#issuecomment-284214979, the click on **Show tutor** ignored.
If I play this move with the @lukasmonk's fix, no prompt is shown at all unless I play something really stupid like Qd1g4. I guess different in score wasn't enough to show the tutor prompt.

**Comment by tico-tico** [comment] 2017-03-05 15:13
BTW should it show **There are XX best moves** if *Avaliable hints* == 0? It shows now.

**Comment by tico-tico** [comment] 2017-03-05 15:24
Another one. I don't know where it comes from.

```
Traceback (most recent call last):
  File "Code\QT\TabElementos.pyo", line 220, in mouseReleaseEvent
    
  File "Code\QT\Tablero.pyo", line 1284, in intentaMover
    
  File ".\Code\GestorEntMaq.py", line 815, in mueveHumano
    if tutor.elegir(self.ayudas > 0, liApPosibles=liApPosibles):
  File "Code\Tutor.pyo", line 67, in elegir
    
  File "Code\Tutor.pyo", line 160, in hazListaRM
    
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by lukasmonk** [comment] 2017-03-05 17:15
> BTW should it show There are XX best moves if Avaliable hints == 0? It shows now.
I believe it can help to the user, it is a minimal help.

**Comment by lukasmonk** [comment] 2017-03-05 17:17
> Another one. I don't know where it comes from.
> 
> Traceback (most recent call last):
>   File "Code\QT\TabElementos.pyo", line 220, in mouseReleaseEvent
>     
>   File "Code\QT\Tablero.pyo", line 1284, in intentaMover
>     
>   File ".\Code\GestorEntMaq.py", line 815, in mueveHumano
>     if tutor.elegir(self.ayudas > 0, liApPosibles=liApPosibles):
>   File "Code\Tutor.pyo", line 67, in elegir
>     
>   File "Code\Tutor.pyo", line 160, in hazListaRM
>     
> TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

This is a problem before changes.

**Comment by tico-tico** [comment] 2017-03-05 17:44
> This is a problem before changes.
nope, i had this with all your changes. not sure how to reproduce it.

**Comment by tico-tico** [comment] 2017-03-05 18:32
I was able to reproduce last exception.

*Play against engine of your choice* starting with this FEN `1r3kN1/p5pp/2p1Qp2/3P4/2B5/P7/P1PP1PPP/RNB1K2R w KQ - 5 16` against **Monkey**.

you - e6e7, ignore tutor *select my move*
monkey - f8g8
you - d5c6
monkey - g8h8

take back twice (you get to the beginning).

play e6e7 again but press show tutor, you should get exception after this.

```
Traceback (most recent call last):
  File "Code\QT\TabElementos.pyo", line 220, in mouseReleaseEvent
    
  File "Code\QT\Tablero.pyo", line 1284, in intentaMover
    
  File ".\Code\GestorEntMaq.py", line 815, in mueveHumano
    if tutor.elegir(self.ayudas > 0, liApPosibles=liApPosibles):
  File "Code\Tutor.pyo", line 67, in elegir
    
  File "Code\Tutor.pyo", line 160, in hazListaRM
    
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by fonkap** [comment] 2017-03-05 18:55
Wow Tico that was a detailed explanation!, I am able to reproduce the problem too.
This bug has something to do with "The tutor thinks while you think" feature. If you uncheck it, the problem dissapears.
BUT, I think you are running old code (my exception is slightly different from yours) please be sure you are using the last code from GitHub. 

Lucas, I think this problem is caused when in the function hazListaRM, the list self.mrmTutor.liMultiPV contains old movements, then self.pgn(desde, hasta, coronacion) inside pb.pgnSP returns None (because the move is impossible in the current board) producing the exception.

I think there is a problem in tutor initialization when "The tutor thinks while you think" feature is on. Im also trying to fix this.

**Comment by fonkap** [comment] 2017-03-05 19:02
I found an easier way to reproduce the problem:
Play against engine of your choice starting with **normal starting position against Monkey.**

you - a2a4, ignore tutor select my move
monkey - a move
take back once (you get to the beginning).

play a2a4 again but press show tutor, you should get exception after this.

**Comment by tico-tico** [comment] 2017-03-05 19:30
> I found an easier way to reproduce the problem:
> Play against engine of your choice starting with normal starting position against Monkey.
> 
> you - a2a4, ignore tutor select my move
> monkey - a move
> take back once (you get to the beginning).
> 
> play a2a4 again but press show tutor, you should get exception after this.

no exception here. tried Deepfish and Komodo

**Comment by lukasmonk** [comment] 2017-03-05 19:31
I believe it is fixed.
As fonkap indicated, problem is in relation to tutor working in background, it is not stopped when go back.
I have uploaded new code with the changes.
Thank you very much tico and fonkap.

**Comment by fonkap** [comment] 2017-03-05 19:40
Now it is working perfectly fine for me. Tested both my case and Tico's.

Thank you Lucas!

**Comment by tico-tico** [comment] 2017-03-05 19:42
Yes! Perfect! :thumbsup:

**Comment by lukasmonk** [comment] 2017-03-05 19:46
Great help!

**Comment by tico-tico** [comment] 2017-03-05 20:17
And another one ;)
```
Traceback (most recent call last):
  File ".\Code\QT\TabElementos.py", line 220, in mouseReleaseEvent
    self.tablero.intentaMover(self, event.scenePos(), event.button())
  File ".\Code\QT\Tablero.py", line 1284, in intentaMover
    if not self.mensajero(desde, hasta):
  File ".\Code\GestorEntMaq.py", line 816, in mueveHumano
    if tutor.elegir(self.ayudas > 0, liApPosibles=liApPosibles):
  File ".\Code\Tutor.py", line 67, in elegir
    self.listaRM = self.hazListaRM(posUsuario)  # rm,nombre
  File ".\Code\Tutor.py", line 160, in hazListaRM
    nombre += " " + rm.abrTexto()
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

not sure how to reproduce it yet

**Comment by lukasmonk** [comment] 2017-03-05 20:35
I have reopen the issue until it is fixed.

**Comment by tico-tico** [comment] 2017-03-05 20:52
Unfortunately I can't reproduce the exception. The only thing I know about it, it had `Show tutor ()` in popup menu, I guess it means checkmate.
@lukasmonk, since the issue is hard to catch, I think you should release the current version 'coz it has important fixes.
Thanks.

**Comment by tico-tico** [comment] 2017-03-06 23:08
> problem is in relation to tutor working in background

Can it be similar to this traceback
```
Traceback (most recent call last):
  File ".\Code\QT\TabElementos.py", line 220, in mouseReleaseEvent
  File ".\Code\QT\Tablero.py", line 1284, in intentaMover
  File ".\Code\GestorWashing.py", line 682, in mueveHumano
  File ".\Code\Tutor.py", line 67, in elegir
  File ".\Code\Tutor.py", line 160, in hazListaRM
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'unicode'
```
i just got in **Washing machine**, when after two takebacks I tried to make a move? Sorry, the traceback is a bit crippled, I guess python optimized out all debug stuff out of **.pyo* files.

**Comment by lukasmonk** [comment] 2017-03-07 17:47
In python, traceback doesn´t change when different level of optimization is selected.
Washing machine and takeback, are the main clues.
I have done some changes, but there is yet a problem.

**Comment by lukasmonk** [comment] 2017-03-07 18:12
I hope it is fixed now.

**Comment by tico-tico** [comment] 2017-03-07 18:56
Now it's better! :+1: 

Something unrelated:

1. Open `Opponent for young players` -> `Albums` -> select any. Click the close button (red cross in top-right corner)

```
TypeError: closeEvent() takes exactly 1 argument (2 given)
```

2. Are you aware that `PRAGMA page_size = 8192` in your code does nothing 'coz (quote from manual):

> The page_size pragma will only set in the page size if it is issued before any other SQL statements that cause I/O against the database file. SQL statements that cause I/O against the database file include "CREATE", "SELECT", "BEGIN IMMEDIATE", and "PRAGMA journal_mode=WAL".

Now program's option databases are created with default 1024 page size. Not a big deal, just for your information.

Speaking of 8192, isn't 4096 is better because it's equal to the most common file system cluster size?

**Comment by lukasmonk** [comment] 2017-03-07 22:14
1. Fixed
2. Fixed
Thank you very much.

**Comment by tico-tico** [comment] 2017-03-07 23:48
> 2. Fixed

you've missed *Code/SQL/Base.py*

**Comment by tico-tico** [comment] 2017-03-08 15:26
`Tools` -> `Openings` -> `Personal opening guide`

**First move** (button under the chessboard) always

```
Traceback (most recent call last):
  File ".\Code\QT\WBG_InfoMove.py", line 110, in procesarTB
  File ".\Code\QT\WBG_InfoMove.py", line 292, in MoverInicio
  File ".\Code\QT\WBG_InfoMove.py", line 240, in colocatePartida
AttributeError: 'WInfomove' object has no attribute 'partida'
```

**Previous move** (button under the chessboard) if no moves left

```
Traceback (most recent call last):
  File ".\Code\QT\WBG_InfoMove.py", line 110, in procesarTB
  File ".\Code\QT\WBG_InfoMove.py", line 303, in MoverAtras
  File ".\Code\QT\WBG_InfoMove.py", line 209, in colocate
  File ".\Code\QT\WBG_InfoMove.py", line 292, in MoverInicio
  File ".\Code\QT\WBG_InfoMove.py", line 240, in colocatePartida
AttributeError: 'WInfomove' object has no attribute 'partida'
```

**Comment by lukasmonk** [comment] 2017-03-08 18:00
Fixed both bugs.
Thank you very much

**Comment by tico-tico** [comment] 2017-03-09 13:14
Yep, exceptions are eliminated.

I have a question, should LC in the opening guide allow to make a new move if I return some moves back? Just to try another opening. Or it's possible only from the start pressing big **Start position** button.

BTW **First move** (button under the chessboard) doesn't remove highlight for current move (blue text) as **Previous move** does.

**Comment by lukasmonk** [comment] 2017-03-09 22:14
There are some bugs in relation of this.
I´ll try to fix.

**Comment by tico-tico** [comment] 2017-03-19 15:37
`Play` -> `Play against an engine of your choice`. Make several moves. `Cancel` (note: tutor is still pondering), `Reinit`.

```
Traceback (most recent call last):
  File ".\Code\QT\TabElementos.py", line 220, in mouseReleaseEvent
    self.tablero.intentaMover(self, event.scenePos(), event.button())
  File ".\Code\QT\Tablero.py", line 1284, in intentaMover
    if not self.mensajero(desde, hasta):
  File ".\Code\GestorEntMaq.py", line 822, in mueveHumano
    if tutor.elegir(self.ayudas > 0, liApPosibles=liApPosibles):
  File ".\Code\Tutor.py", line 67, in elegir
    self.listaRM = self.hazListaRM(posUsuario)  # rm,nombre
  File ".\Code\Tutor.py", line 160, in hazListaRM
    nombre += " " + rm.abrTexto()
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'unicode'
```

**Comment by lukasmonk** [comment] 2017-03-19 16:51
I believe it is fixed now.
Thank you very much.

**Comment by tico-tico** [comment] 2017-03-21 22:02
Tutor stops pondering if I press `Help to move`. It resumes after next move. Is that OK?

**Closed** 2017-09-01 14:14 UTC
